### ISSUE TITLE
¿Por que a las tareas les llamas keeps?

### ISSUE THREAD

**Issue by JuanVqz** [rimorsoft/CRUD-de-Laravel-VUE#2]
Hola que tal, pienso aportar en el proyecto, ¿esta bien?
- En JavaScript 
1.- no es necesario el  punto y coma ';'
2.- las funciones se pueden llamar
Antes
`
methods: {
  getKeeps: function getKeeps(){}
}
`
Ahora
`
methods: {
  getKeeps() {}
}
`

- En la migración 
1.- creo que le falta un campo 'descripción' ( Por Hacer), donde se describa la tarea como lo hace en este caso keep.
2.- Keep, creo que significa mantener, supongo que quieres decir si esa tarea esta hecha o no, por lo tanto seria del tipo boolean, para marcarla hecha o no, ¿esta bien?

- Vue
1.- Separar las librerias,  por que asi es muy confuso.
2.- No es necesario inicializar las variables del data(), con todas sus propiedades
3.- En vez de dejar las Tasks en app moverlo a tasks/index, segun corresponda.

- Laravel
1.- Mover el api como tal a controllers/api/TasksController
3.- Y las vistas en controllers/TasksController
2.- Usar transformers?

Saludos! buena iniciativa.

**Comment by italomoralesf** [comment]
Es un gran aporte mi amigo
